Add bookings
AleksandrLiagushin/java-shareit pull request #2
Opened 2023-12-11 16:28 UTC by AleksandrLiagushin

2023-12-12 16:15 UTC, kalitva requested changes

2023-12-12 16:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Builder
Зачем здесь билдер когда есть геттеры и сеттеры?

2023-12-12 16:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@AllArgsConstructor
Давай не использовать конструктор с более чем 3-мя параметрами (если хочешь создавать объекты одним выражением, выдели для этого метод)

2023-12-12 16:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingRepo.java
> +public interface BookingRepo extends JpaRepository<Booking, Long> {
`BookingRepo --> BookingRepository`

2023-12-12 16:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            case "true":
Принимай в контроллере сразу `boolean` и затем используй здесь `if-else` вместо свитча

2023-12-12 16:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        }
Эти вычисления должны происходить на стороне бд. 

Вместо методов для каждого кейса лучше воспользоваться `Specification`, попробуй, это используется почти везде, где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-12-12 16:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +@NoArgsConstructor
То же, не следует лепить все подряд аннотации ломбока

2023-12-12 16:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/comment/CommentDto.java
> +}
Хорошей практикой будет сделать поля дтошек `final`

2023-12-13 07:23 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Builder
Done

2023-12-13 07:23 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@AllArgsConstructor
Done

2023-12-13 07:24 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/BookingRepo.java
> +public interface BookingRepo extends JpaRepository<Booking, Long> {
Done

2023-12-13 07:25 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +@NoArgsConstructor
done

2023-12-13 07:37 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            case "true":
done

2023-12-13 08:13 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        }
вернусь к переделке после 15го спринта

2023-12-13 19:21 UTC, kalitva approved these changes

2023-12-13 19:21 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +@Transactional(readOnly = true)
Не надо ставить эту аннотацию на уровне класса, только путаницу создает

2023-12-13 19:21 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @Transactional(rollbackFor = Exception.class)
А по дефолту `rollbackFor` не так работает?

2023-12-13 19:21 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    public List<Booking> checkState(List<Booking> bookings, String state) {
private?

2023-12-13 19:21 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoIn.java
> +@AllArgsConstructor
Давай не использовать конструкторы с более чем тремя параметрами

2023-12-13 19:21 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoOut.java
> +@Setter
Как это сочетается с `final` полями

2023-12-13 19:21 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemForOwnerDto.java
> +@Setter
Возможно, здесь лучше подойдет `@With` - https://projectlombok.org/features/With

2023-12-13 19:21 UTC, kalitva commented on src/main/resources/schema.sql
> +--ALTER TABLE items ADD CONSTRAINT fk_item_request_id FOREIGN KEY (request_id) REFERENCES requests(request_id) ON DELETE CASCADE;
Удали закомментированный код

2023-12-14 02:46 UTC, AleksandrLiagushin commented on src/main/resources/schema.sql
> +--ALTER TABLE items ADD CONSTRAINT fk_item_request_id FOREIGN KEY (request_id) REFERENCES requests(request_id) ON DELETE CASCADE;
этот код будет нужен в 15м спринте. могу вырезать и снова добавить=)

2023-12-14 02:47 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    public List<Booking> checkState(List<Booking> bookings, String state) {
этот метод вызывается в контроллере. Private смогу сделать после рефакторинга

2023-12-14 02:48 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoIn.java
> +@AllArgsConstructor
done

2023-12-14 02:51 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoOut.java
> +@Setter
done

2023-12-14 03:00 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @Transactional(rollbackFor = Exception.class)
по умолчанию в случае провервяемого исключения @Transactional создаст коммит и сдвинет счетчик на +1. что приведет к неверной идентификации последующих записей

2023-12-14 03:07 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +@Transactional(readOnly = true)
done

2023-12-14 03:08 UTC, AleksandrLiagushin commented on src/main/java/ru/practicum/shareit/item/dto/ItemForOwnerDto.java
> +@Setter
я не очень хочу клонировать объекты...

2023-12-14 09:15 UTC, merged